defaults:
  - config: MEDSTorchDataConfig
  - _self_

_target_: meds_torchdata.extensions.lightning_datamodule.Datamodule
config:
  tensorized_cohort_dir: ${tensorized_cohort_dir}
  max_seq_len: ${max_seq_len}
  seq_sampling_strategy: RANDOM
  static_inclusion_mode: OMIT
batch_size: ${batch_size}
num_workers: ${num_workers}
