defaults:
  - datamodule: inference
  - model: default
  - optimizer: adamw
  - _self_

max_seq_len: 256
batch_size: 32
num_workers: 0

tensorized_cohort_dir: ???
index: ???
split: held_out
model_initialization_dir: ???
output_dir: ???

hydra:
  run: {dir: "${output_dir}/.logs"}
  job: {chdir: false}
